export const GET_MUSCLES = 'GET_MUSCLES'
export const GET_EXERCISES_BY_MUSCLES = 'GET_EXERCISES_BY_MUSCLES'
export const SET_CATEGORY = 'SET_CATEGORY'
export const SELECTED_EXERCISE = 'SELECTED_EXERCISE'